# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .acl import *
from .aws_external_id import *
from .contacts import *
from .device_authorization import *
from .device_key import *
from .device_subnet_routes import *
from .device_tags import *
from .dns_nameservers import *
from .dns_preferences import *
from .dns_search_paths import *
from .dns_split_nameservers import *
from .get4_via6 import *
from .get_acl import *
from .get_device import *
from .get_devices import *
from .get_user import *
from .get_users import *
from .logstream_configuration import *
from .posture_integration import *
from .provider import *
from .tailnet_key import *
from .tailnet_settings import *
from .webhook import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_tailscale.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_tailscale.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "tailscale",
  "mod": "index/acl",
  "fqn": "pulumi_tailscale",
  "classes": {
   "tailscale:index/acl:Acl": "Acl"
  }
 },
 {
  "pkg": "tailscale",
  "mod": "index/awsExternalId",
  "fqn": "pulumi_tailscale",
  "classes": {
   "tailscale:index/awsExternalId:AwsExternalId": "AwsExternalId"
  }
 },
 {
  "pkg": "tailscale",
  "mod": "index/contacts",
  "fqn": "pulumi_tailscale",
  "classes": {
   "tailscale:index/contacts:Contacts": "Contacts"
  }
 },
 {
  "pkg": "tailscale",
  "mod": "index/deviceAuthorization",
  "fqn": "pulumi_tailscale",
  "classes": {
   "tailscale:index/deviceAuthorization:DeviceAuthorization": "DeviceAuthorization"
  }
 },
 {
  "pkg": "tailscale",
  "mod": "index/deviceKey",
  "fqn": "pulumi_tailscale",
  "classes": {
   "tailscale:index/deviceKey:DeviceKey": "DeviceKey"
  }
 },
 {
  "pkg": "tailscale",
  "mod": "index/deviceSubnetRoutes",
  "fqn": "pulumi_tailscale",
  "classes": {
   "tailscale:index/deviceSubnetRoutes:DeviceSubnetRoutes": "DeviceSubnetRoutes"
  }
 },
 {
  "pkg": "tailscale",
  "mod": "index/deviceTags",
  "fqn": "pulumi_tailscale",
  "classes": {
   "tailscale:index/deviceTags:DeviceTags": "DeviceTags"
  }
 },
 {
  "pkg": "tailscale",
  "mod": "index/dnsNameservers",
  "fqn": "pulumi_tailscale",
  "classes": {
   "tailscale:index/dnsNameservers:DnsNameservers": "DnsNameservers"
  }
 },
 {
  "pkg": "tailscale",
  "mod": "index/dnsPreferences",
  "fqn": "pulumi_tailscale",
  "classes": {
   "tailscale:index/dnsPreferences:DnsPreferences": "DnsPreferences"
  }
 },
 {
  "pkg": "tailscale",
  "mod": "index/dnsSearchPaths",
  "fqn": "pulumi_tailscale",
  "classes": {
   "tailscale:index/dnsSearchPaths:DnsSearchPaths": "DnsSearchPaths"
  }
 },
 {
  "pkg": "tailscale",
  "mod": "index/dnsSplitNameservers",
  "fqn": "pulumi_tailscale",
  "classes": {
   "tailscale:index/dnsSplitNameservers:DnsSplitNameservers": "DnsSplitNameservers"
  }
 },
 {
  "pkg": "tailscale",
  "mod": "index/logstreamConfiguration",
  "fqn": "pulumi_tailscale",
  "classes": {
   "tailscale:index/logstreamConfiguration:LogstreamConfiguration": "LogstreamConfiguration"
  }
 },
 {
  "pkg": "tailscale",
  "mod": "index/postureIntegration",
  "fqn": "pulumi_tailscale",
  "classes": {
   "tailscale:index/postureIntegration:PostureIntegration": "PostureIntegration"
  }
 },
 {
  "pkg": "tailscale",
  "mod": "index/tailnetKey",
  "fqn": "pulumi_tailscale",
  "classes": {
   "tailscale:index/tailnetKey:TailnetKey": "TailnetKey"
  }
 },
 {
  "pkg": "tailscale",
  "mod": "index/tailnetSettings",
  "fqn": "pulumi_tailscale",
  "classes": {
   "tailscale:index/tailnetSettings:TailnetSettings": "TailnetSettings"
  }
 },
 {
  "pkg": "tailscale",
  "mod": "index/webhook",
  "fqn": "pulumi_tailscale",
  "classes": {
   "tailscale:index/webhook:Webhook": "Webhook"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "tailscale",
  "token": "pulumi:providers:tailscale",
  "fqn": "pulumi_tailscale",
  "class": "Provider"
 }
]
"""
)
