provider: tailscale
major-version: 1
esc:
    enabled: true
env:
    TAILSCALE_OAUTH_CLIENT_SECRET: ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
    TAILSCALE_OAUTH_CLIENT_ID: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
    TAILSCALE_TAILNET: ${{ secrets.TAILSCALE_TAILNET }}
makeTemplate: bridged
team: ecosystem
pulumiConvert: 1
registryDocs: true
integrationTestProvider: true
