provider: tailscale
major-version: 1
esc:
  enabled: true
env:
  TAILSCALE_OAUTH_CLIENT_SECRET: ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
  TAILSCALE_OAUTH_CLIENT_ID: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
  TAILSCALE_TAILNET: ${{ secrets.TAILSCALE_TAILNET }}
makeTemplate: bridged
plugins:
  - name: terraform
    version: "1.0.16"
    kind: converter
  - name: random
    version: "4.3.1"
team: ecosystem
pulumiConvert: 1
registryDocs: true
integrationTestProvider: true
