// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tailscale
{
    /// <summary>
    /// The dns_preferences resource allows you to configure DNS preferences for your Tailscale network. See https://tailscale.com/kb/1054/dns for more information.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Tailscale = Pulumi.Tailscale;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var samplePreferences = new Tailscale.DnsPreferences("sample_preferences", new()
    ///     {
    ///         MagicDns = true,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// ID doesn't matter.
    /// 
    /// ```sh
    /// $ pulumi import tailscale:index/dnsPreferences:DnsPreferences sample_preferences dns_preferences
    /// ```
    /// </summary>
    [TailscaleResourceType("tailscale:index/dnsPreferences:DnsPreferences")]
    public partial class DnsPreferences : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Whether or not to enable magic DNS
        /// </summary>
        [Output("magicDns")]
        public Output<bool> MagicDns { get; private set; } = null!;


        /// <summary>
        /// Create a DnsPreferences resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DnsPreferences(string name, DnsPreferencesArgs args, CustomResourceOptions? options = null)
            : base("tailscale:index/dnsPreferences:DnsPreferences", name, args ?? new DnsPreferencesArgs(), MakeResourceOptions(options, ""))
        {
        }

        private DnsPreferences(string name, Input<string> id, DnsPreferencesState? state = null, CustomResourceOptions? options = null)
            : base("tailscale:index/dnsPreferences:DnsPreferences", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DnsPreferences resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DnsPreferences Get(string name, Input<string> id, DnsPreferencesState? state = null, CustomResourceOptions? options = null)
        {
            return new DnsPreferences(name, id, state, options);
        }
    }

    public sealed class DnsPreferencesArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether or not to enable magic DNS
        /// </summary>
        [Input("magicDns", required: true)]
        public Input<bool> MagicDns { get; set; } = null!;

        public DnsPreferencesArgs()
        {
        }
        public static new DnsPreferencesArgs Empty => new DnsPreferencesArgs();
    }

    public sealed class DnsPreferencesState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether or not to enable magic DNS
        /// </summary>
        [Input("magicDns")]
        public Input<bool>? MagicDns { get; set; }

        public DnsPreferencesState()
        {
        }
        public static new DnsPreferencesState Empty => new DnsPreferencesState();
    }
}
