// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tailscale
{
    /// <summary>
    /// The FederatedIdentity resource allows you to create federated identities to programmatically interact with the Tailscale API using workload identity federation.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Tailscale = Pulumi.Tailscale;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var exampleFederatedIdentity = new Tailscale.FederatedIdentity("example_federated_identity", new()
    ///     {
    ///         Description = "Example federated identity",
    ///         Scopes = new[]
    ///         {
    ///             "auth_keys",
    ///             "devices:core",
    ///         },
    ///         Tags = new[]
    ///         {
    ///             "tag:test",
    ///         },
    ///         Issuer = "https://example.com",
    ///         Subject = "example-sub-*",
    ///         CustomClaimRules = 
    ///         {
    ///             { "repo_name", "example-repo-name" },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// The `pulumi import` command can be used, for example:
    /// 
    /// ```sh
    /// $ pulumi import tailscale:index/federatedIdentity:FederatedIdentity example k1234511CNTRL-kZDRvszg8621CNTRL
    /// ```
    /// </summary>
    [TailscaleResourceType("tailscale:index/federatedIdentity:FederatedIdentity")]
    public partial class FederatedIdentity : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The value used when matching against the `Aud` claim from an OIDC identity token. Specifying the audience is optional as Tailscale will generate a secure audience at creation time by default.   It is recommended to let Tailscale generate the audience unless the identity provider you are integrating with requires a specific audience format.
        /// </summary>
        [Output("audience")]
        public Output<string> Audience { get; private set; } = null!;

        /// <summary>
        /// The creation timestamp of the key in RFC3339 format
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// A map of claim names to pattern strings used to match against arbitrary claims in the OIDC identity token. Patterns can include `*` characters to match against any character.
        /// </summary>
        [Output("customClaimRules")]
        public Output<ImmutableDictionary<string, string>?> CustomClaimRules { get; private set; } = null!;

        /// <summary>
        /// A description of the federated identity consisting of alphanumeric characters. Defaults to `""`.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// The issuer of the OIDC identity token used in the token exchange. Must be a valid and publicly reachable https:// URL.
        /// </summary>
        [Output("issuer")]
        public Output<string> Issuer { get; private set; } = null!;

        /// <summary>
        /// Scopes to grant to the federated identity. See https://tailscale.com/kb/1623/ for a list of available scopes.
        /// </summary>
        [Output("scopes")]
        public Output<ImmutableArray<string>> Scopes { get; private set; } = null!;

        /// <summary>
        /// The pattern used when matching against the `Sub` claim from an OIDC identity token. Patterns can include `*` characters to match against any character.
        /// </summary>
        [Output("subject")]
        public Output<string> Subject { get; private set; } = null!;

        /// <summary>
        /// A list of tags that access tokens generated for the federated identity will be able to assign to devices. Mandatory if the scopes include "devices:core" or "AuthKeys".
        /// </summary>
        [Output("tags")]
        public Output<ImmutableArray<string>> Tags { get; private set; } = null!;

        /// <summary>
        /// The updated timestamp of the key in RFC3339 format
        /// </summary>
        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;

        /// <summary>
        /// ID of the user who created this federated identity, empty for federated identities created by other trust credentials.
        /// </summary>
        [Output("userId")]
        public Output<string> UserId { get; private set; } = null!;


        /// <summary>
        /// Create a FederatedIdentity resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public FederatedIdentity(string name, FederatedIdentityArgs args, CustomResourceOptions? options = null)
            : base("tailscale:index/federatedIdentity:FederatedIdentity", name, args ?? new FederatedIdentityArgs(), MakeResourceOptions(options, ""))
        {
        }

        private FederatedIdentity(string name, Input<string> id, FederatedIdentityState? state = null, CustomResourceOptions? options = null)
            : base("tailscale:index/federatedIdentity:FederatedIdentity", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing FederatedIdentity resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static FederatedIdentity Get(string name, Input<string> id, FederatedIdentityState? state = null, CustomResourceOptions? options = null)
        {
            return new FederatedIdentity(name, id, state, options);
        }
    }

    public sealed class FederatedIdentityArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The value used when matching against the `Aud` claim from an OIDC identity token. Specifying the audience is optional as Tailscale will generate a secure audience at creation time by default.   It is recommended to let Tailscale generate the audience unless the identity provider you are integrating with requires a specific audience format.
        /// </summary>
        [Input("audience")]
        public Input<string>? Audience { get; set; }

        [Input("customClaimRules")]
        private InputMap<string>? _customClaimRules;

        /// <summary>
        /// A map of claim names to pattern strings used to match against arbitrary claims in the OIDC identity token. Patterns can include `*` characters to match against any character.
        /// </summary>
        public InputMap<string> CustomClaimRules
        {
            get => _customClaimRules ?? (_customClaimRules = new InputMap<string>());
            set => _customClaimRules = value;
        }

        /// <summary>
        /// A description of the federated identity consisting of alphanumeric characters. Defaults to `""`.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The issuer of the OIDC identity token used in the token exchange. Must be a valid and publicly reachable https:// URL.
        /// </summary>
        [Input("issuer", required: true)]
        public Input<string> Issuer { get; set; } = null!;

        [Input("scopes", required: true)]
        private InputList<string>? _scopes;

        /// <summary>
        /// Scopes to grant to the federated identity. See https://tailscale.com/kb/1623/ for a list of available scopes.
        /// </summary>
        public InputList<string> Scopes
        {
            get => _scopes ?? (_scopes = new InputList<string>());
            set => _scopes = value;
        }

        /// <summary>
        /// The pattern used when matching against the `Sub` claim from an OIDC identity token. Patterns can include `*` characters to match against any character.
        /// </summary>
        [Input("subject", required: true)]
        public Input<string> Subject { get; set; } = null!;

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// A list of tags that access tokens generated for the federated identity will be able to assign to devices. Mandatory if the scopes include "devices:core" or "AuthKeys".
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        public FederatedIdentityArgs()
        {
        }
        public static new FederatedIdentityArgs Empty => new FederatedIdentityArgs();
    }

    public sealed class FederatedIdentityState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The value used when matching against the `Aud` claim from an OIDC identity token. Specifying the audience is optional as Tailscale will generate a secure audience at creation time by default.   It is recommended to let Tailscale generate the audience unless the identity provider you are integrating with requires a specific audience format.
        /// </summary>
        [Input("audience")]
        public Input<string>? Audience { get; set; }

        /// <summary>
        /// The creation timestamp of the key in RFC3339 format
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        [Input("customClaimRules")]
        private InputMap<string>? _customClaimRules;

        /// <summary>
        /// A map of claim names to pattern strings used to match against arbitrary claims in the OIDC identity token. Patterns can include `*` characters to match against any character.
        /// </summary>
        public InputMap<string> CustomClaimRules
        {
            get => _customClaimRules ?? (_customClaimRules = new InputMap<string>());
            set => _customClaimRules = value;
        }

        /// <summary>
        /// A description of the federated identity consisting of alphanumeric characters. Defaults to `""`.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The issuer of the OIDC identity token used in the token exchange. Must be a valid and publicly reachable https:// URL.
        /// </summary>
        [Input("issuer")]
        public Input<string>? Issuer { get; set; }

        [Input("scopes")]
        private InputList<string>? _scopes;

        /// <summary>
        /// Scopes to grant to the federated identity. See https://tailscale.com/kb/1623/ for a list of available scopes.
        /// </summary>
        public InputList<string> Scopes
        {
            get => _scopes ?? (_scopes = new InputList<string>());
            set => _scopes = value;
        }

        /// <summary>
        /// The pattern used when matching against the `Sub` claim from an OIDC identity token. Patterns can include `*` characters to match against any character.
        /// </summary>
        [Input("subject")]
        public Input<string>? Subject { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// A list of tags that access tokens generated for the federated identity will be able to assign to devices. Mandatory if the scopes include "devices:core" or "AuthKeys".
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        /// <summary>
        /// The updated timestamp of the key in RFC3339 format
        /// </summary>
        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        /// <summary>
        /// ID of the user who created this federated identity, empty for federated identities created by other trust credentials.
        /// </summary>
        [Input("userId")]
        public Input<string>? UserId { get; set; }

        public FederatedIdentityState()
        {
        }
        public static new FederatedIdentityState Empty => new FederatedIdentityState();
    }
}
