// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tailscale
{
    /// <summary>
    /// The tailnet_settings resource allows you to configure settings for your tailnet. See https://tailscale.com/api#tag/tailnetsettings for more information.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Tailscale = Pulumi.Tailscale;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var sampleTailnetSettings = new Tailscale.TailnetSettings("sample_tailnet_settings", new()
    ///     {
    ///         DevicesApprovalOn = true,
    ///         DevicesAutoUpdatesOn = true,
    ///         DevicesKeyDurationDays = 5,
    ///         UsersApprovalOn = true,
    ///         UsersRoleAllowedToJoinExternalTailnet = "member",
    ///         PostureIdentityCollectionOn = true,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// ID doesn't matter.
    /// 
    /// ```sh
    /// $ pulumi import tailscale:index/tailnetSettings:TailnetSettings sample_preferences tailnet_settings
    /// ```
    /// </summary>
    [TailscaleResourceType("tailscale:index/tailnetSettings:TailnetSettings")]
    public partial class TailnetSettings : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Whether device approval is enabled for the tailnet
        /// </summary>
        [Output("devicesApprovalOn")]
        public Output<bool?> DevicesApprovalOn { get; private set; } = null!;

        /// <summary>
        /// Whether auto updates are enabled for devices that belong to this tailnet
        /// </summary>
        [Output("devicesAutoUpdatesOn")]
        public Output<bool?> DevicesAutoUpdatesOn { get; private set; } = null!;

        /// <summary>
        /// The key expiry duration for devices on this tailnet
        /// </summary>
        [Output("devicesKeyDurationDays")]
        public Output<int?> DevicesKeyDurationDays { get; private set; } = null!;

        /// <summary>
        /// Whether network flog logs are enabled for the tailnet
        /// </summary>
        [Output("networkFlowLoggingOn")]
        public Output<bool?> NetworkFlowLoggingOn { get; private set; } = null!;

        /// <summary>
        /// Whether identity collection is enabled for device posture integrations for the tailnet
        /// </summary>
        [Output("postureIdentityCollectionOn")]
        public Output<bool?> PostureIdentityCollectionOn { get; private set; } = null!;

        /// <summary>
        /// Whether regional routing is enabled for the tailnet
        /// </summary>
        [Output("regionalRoutingOn")]
        public Output<bool?> RegionalRoutingOn { get; private set; } = null!;

        /// <summary>
        /// Whether user approval is enabled for this tailnet
        /// </summary>
        [Output("usersApprovalOn")]
        public Output<bool?> UsersApprovalOn { get; private set; } = null!;

        /// <summary>
        /// Which user roles are allowed to join external tailnets
        /// </summary>
        [Output("usersRoleAllowedToJoinExternalTailnet")]
        public Output<string?> UsersRoleAllowedToJoinExternalTailnet { get; private set; } = null!;


        /// <summary>
        /// Create a TailnetSettings resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public TailnetSettings(string name, TailnetSettingsArgs? args = null, CustomResourceOptions? options = null)
            : base("tailscale:index/tailnetSettings:TailnetSettings", name, args ?? new TailnetSettingsArgs(), MakeResourceOptions(options, ""))
        {
        }

        private TailnetSettings(string name, Input<string> id, TailnetSettingsState? state = null, CustomResourceOptions? options = null)
            : base("tailscale:index/tailnetSettings:TailnetSettings", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing TailnetSettings resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static TailnetSettings Get(string name, Input<string> id, TailnetSettingsState? state = null, CustomResourceOptions? options = null)
        {
            return new TailnetSettings(name, id, state, options);
        }
    }

    public sealed class TailnetSettingsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether device approval is enabled for the tailnet
        /// </summary>
        [Input("devicesApprovalOn")]
        public Input<bool>? DevicesApprovalOn { get; set; }

        /// <summary>
        /// Whether auto updates are enabled for devices that belong to this tailnet
        /// </summary>
        [Input("devicesAutoUpdatesOn")]
        public Input<bool>? DevicesAutoUpdatesOn { get; set; }

        /// <summary>
        /// The key expiry duration for devices on this tailnet
        /// </summary>
        [Input("devicesKeyDurationDays")]
        public Input<int>? DevicesKeyDurationDays { get; set; }

        /// <summary>
        /// Whether network flog logs are enabled for the tailnet
        /// </summary>
        [Input("networkFlowLoggingOn")]
        public Input<bool>? NetworkFlowLoggingOn { get; set; }

        /// <summary>
        /// Whether identity collection is enabled for device posture integrations for the tailnet
        /// </summary>
        [Input("postureIdentityCollectionOn")]
        public Input<bool>? PostureIdentityCollectionOn { get; set; }

        /// <summary>
        /// Whether regional routing is enabled for the tailnet
        /// </summary>
        [Input("regionalRoutingOn")]
        public Input<bool>? RegionalRoutingOn { get; set; }

        /// <summary>
        /// Whether user approval is enabled for this tailnet
        /// </summary>
        [Input("usersApprovalOn")]
        public Input<bool>? UsersApprovalOn { get; set; }

        /// <summary>
        /// Which user roles are allowed to join external tailnets
        /// </summary>
        [Input("usersRoleAllowedToJoinExternalTailnet")]
        public Input<string>? UsersRoleAllowedToJoinExternalTailnet { get; set; }

        public TailnetSettingsArgs()
        {
        }
        public static new TailnetSettingsArgs Empty => new TailnetSettingsArgs();
    }

    public sealed class TailnetSettingsState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether device approval is enabled for the tailnet
        /// </summary>
        [Input("devicesApprovalOn")]
        public Input<bool>? DevicesApprovalOn { get; set; }

        /// <summary>
        /// Whether auto updates are enabled for devices that belong to this tailnet
        /// </summary>
        [Input("devicesAutoUpdatesOn")]
        public Input<bool>? DevicesAutoUpdatesOn { get; set; }

        /// <summary>
        /// The key expiry duration for devices on this tailnet
        /// </summary>
        [Input("devicesKeyDurationDays")]
        public Input<int>? DevicesKeyDurationDays { get; set; }

        /// <summary>
        /// Whether network flog logs are enabled for the tailnet
        /// </summary>
        [Input("networkFlowLoggingOn")]
        public Input<bool>? NetworkFlowLoggingOn { get; set; }

        /// <summary>
        /// Whether identity collection is enabled for device posture integrations for the tailnet
        /// </summary>
        [Input("postureIdentityCollectionOn")]
        public Input<bool>? PostureIdentityCollectionOn { get; set; }

        /// <summary>
        /// Whether regional routing is enabled for the tailnet
        /// </summary>
        [Input("regionalRoutingOn")]
        public Input<bool>? RegionalRoutingOn { get; set; }

        /// <summary>
        /// Whether user approval is enabled for this tailnet
        /// </summary>
        [Input("usersApprovalOn")]
        public Input<bool>? UsersApprovalOn { get; set; }

        /// <summary>
        /// Which user roles are allowed to join external tailnets
        /// </summary>
        [Input("usersRoleAllowedToJoinExternalTailnet")]
        public Input<string>? UsersRoleAllowedToJoinExternalTailnet { get; set; }

        public TailnetSettingsState()
        {
        }
        public static new TailnetSettingsState Empty => new TailnetSettingsState();
    }
}
