// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.tailscale.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.tailscale.inputs.DnsConfigurationSplitDnNameserverArgs;
import java.lang.String;
import java.util.List;
import java.util.Objects;


public final class DnsConfigurationSplitDnArgs extends com.pulumi.resources.ResourceArgs {

    public static final DnsConfigurationSplitDnArgs Empty = new DnsConfigurationSplitDnArgs();

    /**
     * The nameservers will be used only for this domain.
     * 
     */
    @Import(name="domain", required=true)
    private Output<String> domain;

    /**
     * @return The nameservers will be used only for this domain.
     * 
     */
    public Output<String> domain() {
        return this.domain;
    }

    /**
     * Set the nameservers used by devices on your network to resolve DNS queries.
     * 
     */
    @Import(name="nameservers", required=true)
    private Output<List<DnsConfigurationSplitDnNameserverArgs>> nameservers;

    /**
     * @return Set the nameservers used by devices on your network to resolve DNS queries.
     * 
     */
    public Output<List<DnsConfigurationSplitDnNameserverArgs>> nameservers() {
        return this.nameservers;
    }

    private DnsConfigurationSplitDnArgs() {}

    private DnsConfigurationSplitDnArgs(DnsConfigurationSplitDnArgs $) {
        this.domain = $.domain;
        this.nameservers = $.nameservers;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DnsConfigurationSplitDnArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DnsConfigurationSplitDnArgs $;

        public Builder() {
            $ = new DnsConfigurationSplitDnArgs();
        }

        public Builder(DnsConfigurationSplitDnArgs defaults) {
            $ = new DnsConfigurationSplitDnArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param domain The nameservers will be used only for this domain.
         * 
         * @return builder
         * 
         */
        public Builder domain(Output<String> domain) {
            $.domain = domain;
            return this;
        }

        /**
         * @param domain The nameservers will be used only for this domain.
         * 
         * @return builder
         * 
         */
        public Builder domain(String domain) {
            return domain(Output.of(domain));
        }

        /**
         * @param nameservers Set the nameservers used by devices on your network to resolve DNS queries.
         * 
         * @return builder
         * 
         */
        public Builder nameservers(Output<List<DnsConfigurationSplitDnNameserverArgs>> nameservers) {
            $.nameservers = nameservers;
            return this;
        }

        /**
         * @param nameservers Set the nameservers used by devices on your network to resolve DNS queries.
         * 
         * @return builder
         * 
         */
        public Builder nameservers(List<DnsConfigurationSplitDnNameserverArgs> nameservers) {
            return nameservers(Output.of(nameservers));
        }

        /**
         * @param nameservers Set the nameservers used by devices on your network to resolve DNS queries.
         * 
         * @return builder
         * 
         */
        public Builder nameservers(DnsConfigurationSplitDnNameserverArgs... nameservers) {
            return nameservers(List.of(nameservers));
        }

        public DnsConfigurationSplitDnArgs build() {
            if ($.domain == null) {
                throw new MissingRequiredPropertyException("DnsConfigurationSplitDnArgs", "domain");
            }
            if ($.nameservers == null) {
                throw new MissingRequiredPropertyException("DnsConfigurationSplitDnArgs", "nameservers");
            }
            return $;
        }
    }

}
