// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.tailscale.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DnsNameserversState extends com.pulumi.resources.ResourceArgs {

    public static final DnsNameserversState Empty = new DnsNameserversState();

    /**
     * Devices on your network will use these nameservers to resolve DNS names. IPv4 or IPv6 addresses are accepted.
     * 
     */
    @Import(name="nameservers")
    private @Nullable Output<List<String>> nameservers;

    /**
     * @return Devices on your network will use these nameservers to resolve DNS names. IPv4 or IPv6 addresses are accepted.
     * 
     */
    public Optional<Output<List<String>>> nameservers() {
        return Optional.ofNullable(this.nameservers);
    }

    private DnsNameserversState() {}

    private DnsNameserversState(DnsNameserversState $) {
        this.nameservers = $.nameservers;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DnsNameserversState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DnsNameserversState $;

        public Builder() {
            $ = new DnsNameserversState();
        }

        public Builder(DnsNameserversState defaults) {
            $ = new DnsNameserversState(Objects.requireNonNull(defaults));
        }

        /**
         * @param nameservers Devices on your network will use these nameservers to resolve DNS names. IPv4 or IPv6 addresses are accepted.
         * 
         * @return builder
         * 
         */
        public Builder nameservers(@Nullable Output<List<String>> nameservers) {
            $.nameservers = nameservers;
            return this;
        }

        /**
         * @param nameservers Devices on your network will use these nameservers to resolve DNS names. IPv4 or IPv6 addresses are accepted.
         * 
         * @return builder
         * 
         */
        public Builder nameservers(List<String> nameservers) {
            return nameservers(Output.of(nameservers));
        }

        /**
         * @param nameservers Devices on your network will use these nameservers to resolve DNS names. IPv4 or IPv6 addresses are accepted.
         * 
         * @return builder
         * 
         */
        public Builder nameservers(String... nameservers) {
            return nameservers(List.of(nameservers));
        }

        public DnsNameserversState build() {
            return $;
        }
    }

}
