// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.tailscale.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;


public final class Get4Via6Args extends com.pulumi.resources.InvokeArgs {

    public static final Get4Via6Args Empty = new Get4Via6Args();

    @Import(name="cidr", required=true)
    private Output<String> cidr;

    public Output<String> cidr() {
        return this.cidr;
    }

    @Import(name="site", required=true)
    private Output<Integer> site;

    public Output<Integer> site() {
        return this.site;
    }

    private Get4Via6Args() {}

    private Get4Via6Args(Get4Via6Args $) {
        this.cidr = $.cidr;
        this.site = $.site;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(Get4Via6Args defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private Get4Via6Args $;

        public Builder() {
            $ = new Get4Via6Args();
        }

        public Builder(Get4Via6Args defaults) {
            $ = new Get4Via6Args(Objects.requireNonNull(defaults));
        }

        public Builder cidr(Output<String> cidr) {
            $.cidr = cidr;
            return this;
        }

        public Builder cidr(String cidr) {
            return cidr(Output.of(cidr));
        }

        public Builder site(Output<Integer> site) {
            $.site = site;
            return this;
        }

        public Builder site(Integer site) {
            return site(Output.of(site));
        }

        public Get4Via6Args build() {
            $.cidr = Objects.requireNonNull($.cidr, "expected parameter 'cidr' to be non-null");
            $.site = Objects.requireNonNull($.site, "expected parameter 'site' to be non-null");
            return $;
        }
    }

}
