// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.tailscale.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetUserPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetUserPlainArgs Empty = new GetUserPlainArgs();

    /**
     * The unique identifier for the user.
     * 
     */
    @Import(name="id")
    private @Nullable String id;

    /**
     * @return The unique identifier for the user.
     * 
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    /**
     * The emailish login name of the user.
     * 
     */
    @Import(name="loginName")
    private @Nullable String loginName;

    /**
     * @return The emailish login name of the user.
     * 
     */
    public Optional<String> loginName() {
        return Optional.ofNullable(this.loginName);
    }

    private GetUserPlainArgs() {}

    private GetUserPlainArgs(GetUserPlainArgs $) {
        this.id = $.id;
        this.loginName = $.loginName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetUserPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetUserPlainArgs $;

        public Builder() {
            $ = new GetUserPlainArgs();
        }

        public Builder(GetUserPlainArgs defaults) {
            $ = new GetUserPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param id The unique identifier for the user.
         * 
         * @return builder
         * 
         */
        public Builder id(@Nullable String id) {
            $.id = id;
            return this;
        }

        /**
         * @param loginName The emailish login name of the user.
         * 
         * @return builder
         * 
         */
        public Builder loginName(@Nullable String loginName) {
            $.loginName = loginName;
            return this;
        }

        public GetUserPlainArgs build() {
            return $;
        }
    }

}
