// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.tailscale.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PostureIntegrationState extends com.pulumi.resources.ResourceArgs {

    public static final PostureIntegrationState Empty = new PostureIntegrationState();

    /**
     * Unique identifier for your client.
     * 
     */
    @Import(name="clientId")
    private @Nullable Output<String> clientId;

    /**
     * @return Unique identifier for your client.
     * 
     */
    public Optional<Output<String>> clientId() {
        return Optional.ofNullable(this.clientId);
    }

    /**
     * The secret (auth key, token, etc.) used to authenticate with the provider.
     * 
     */
    @Import(name="clientSecret")
    private @Nullable Output<String> clientSecret;

    /**
     * @return The secret (auth key, token, etc.) used to authenticate with the provider.
     * 
     */
    public Optional<Output<String>> clientSecret() {
        return Optional.ofNullable(this.clientSecret);
    }

    /**
     * Identifies which of the provider&#39;s clouds to integrate with.
     * 
     */
    @Import(name="cloudId")
    private @Nullable Output<String> cloudId;

    /**
     * @return Identifies which of the provider&#39;s clouds to integrate with.
     * 
     */
    public Optional<Output<String>> cloudId() {
        return Optional.ofNullable(this.cloudId);
    }

    /**
     * The third-party provider for posture data. Valid values are `falcon`, `fleet`, `huntress`, `intune`, `jamfpro`, `kandji`, `kolide`, and `sentinelone`.
     * 
     */
    @Import(name="postureProvider")
    private @Nullable Output<String> postureProvider;

    /**
     * @return The third-party provider for posture data. Valid values are `falcon`, `fleet`, `huntress`, `intune`, `jamfpro`, `kandji`, `kolide`, and `sentinelone`.
     * 
     */
    public Optional<Output<String>> postureProvider() {
        return Optional.ofNullable(this.postureProvider);
    }

    /**
     * The Microsoft Intune directory (tenant) ID. For other providers, this is left blank.
     * 
     */
    @Import(name="tenantId")
    private @Nullable Output<String> tenantId;

    /**
     * @return The Microsoft Intune directory (tenant) ID. For other providers, this is left blank.
     * 
     */
    public Optional<Output<String>> tenantId() {
        return Optional.ofNullable(this.tenantId);
    }

    private PostureIntegrationState() {}

    private PostureIntegrationState(PostureIntegrationState $) {
        this.clientId = $.clientId;
        this.clientSecret = $.clientSecret;
        this.cloudId = $.cloudId;
        this.postureProvider = $.postureProvider;
        this.tenantId = $.tenantId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PostureIntegrationState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PostureIntegrationState $;

        public Builder() {
            $ = new PostureIntegrationState();
        }

        public Builder(PostureIntegrationState defaults) {
            $ = new PostureIntegrationState(Objects.requireNonNull(defaults));
        }

        /**
         * @param clientId Unique identifier for your client.
         * 
         * @return builder
         * 
         */
        public Builder clientId(@Nullable Output<String> clientId) {
            $.clientId = clientId;
            return this;
        }

        /**
         * @param clientId Unique identifier for your client.
         * 
         * @return builder
         * 
         */
        public Builder clientId(String clientId) {
            return clientId(Output.of(clientId));
        }

        /**
         * @param clientSecret The secret (auth key, token, etc.) used to authenticate with the provider.
         * 
         * @return builder
         * 
         */
        public Builder clientSecret(@Nullable Output<String> clientSecret) {
            $.clientSecret = clientSecret;
            return this;
        }

        /**
         * @param clientSecret The secret (auth key, token, etc.) used to authenticate with the provider.
         * 
         * @return builder
         * 
         */
        public Builder clientSecret(String clientSecret) {
            return clientSecret(Output.of(clientSecret));
        }

        /**
         * @param cloudId Identifies which of the provider&#39;s clouds to integrate with.
         * 
         * @return builder
         * 
         */
        public Builder cloudId(@Nullable Output<String> cloudId) {
            $.cloudId = cloudId;
            return this;
        }

        /**
         * @param cloudId Identifies which of the provider&#39;s clouds to integrate with.
         * 
         * @return builder
         * 
         */
        public Builder cloudId(String cloudId) {
            return cloudId(Output.of(cloudId));
        }

        /**
         * @param postureProvider The third-party provider for posture data. Valid values are `falcon`, `fleet`, `huntress`, `intune`, `jamfpro`, `kandji`, `kolide`, and `sentinelone`.
         * 
         * @return builder
         * 
         */
        public Builder postureProvider(@Nullable Output<String> postureProvider) {
            $.postureProvider = postureProvider;
            return this;
        }

        /**
         * @param postureProvider The third-party provider for posture data. Valid values are `falcon`, `fleet`, `huntress`, `intune`, `jamfpro`, `kandji`, `kolide`, and `sentinelone`.
         * 
         * @return builder
         * 
         */
        public Builder postureProvider(String postureProvider) {
            return postureProvider(Output.of(postureProvider));
        }

        /**
         * @param tenantId The Microsoft Intune directory (tenant) ID. For other providers, this is left blank.
         * 
         * @return builder
         * 
         */
        public Builder tenantId(@Nullable Output<String> tenantId) {
            $.tenantId = tenantId;
            return this;
        }

        /**
         * @param tenantId The Microsoft Intune directory (tenant) ID. For other providers, this is left blank.
         * 
         * @return builder
         * 
         */
        public Builder tenantId(String tenantId) {
            return tenantId(Output.of(tenantId));
        }

        public PostureIntegrationState build() {
            return $;
        }
    }

}
