// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tailscale.Outputs
{

    [OutputType]
    public sealed class GetDevicesDeviceResult
    {
        /// <summary>
        /// Tailscale IPs for the device
        /// </summary>
        public readonly ImmutableArray<string> Addresses;
        /// <summary>
        /// The unique identifier of the device
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The name of the device
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private GetDevicesDeviceResult(
            ImmutableArray<string> addresses,

            string id,

            string name)
        {
            Addresses = addresses;
            Id = id;
            Name = name;
        }
    }
}
