// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.tailscale;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.tailscale.DnsSplitNameserversArgs;
import com.pulumi.tailscale.Utilities;
import com.pulumi.tailscale.inputs.DnsSplitNameserversState;
import java.lang.String;
import java.util.List;
import javax.annotation.Nullable;

/**
 * The dns_split_nameservers resource allows you to configure split DNS nameservers for your Tailscale network. See https://tailscale.com/kb/1054/dns for more information.
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.tailscale.DnsSplitNameservers;
 * import com.pulumi.tailscale.DnsSplitNameserversArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var sampleSplitNameservers = new DnsSplitNameservers(&#34;sampleSplitNameservers&#34;, DnsSplitNameserversArgs.builder()        
 *             .domain(&#34;foo.example.com&#34;)
 *             .nameservers(&#34;1.1.1.1&#34;)
 *             .build());
 * 
 *     }
 * }
 * ```
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ## Import
 * 
 * Split DNS nameservers can be imported using the domain name, e.g.
 * 
 * ```sh
 * $ pulumi import tailscale:index/dnsSplitNameservers:DnsSplitNameservers sample_split_nameservers example.com
 * ```
 * 
 */
@ResourceType(type="tailscale:index/dnsSplitNameservers:DnsSplitNameservers")
public class DnsSplitNameservers extends com.pulumi.resources.CustomResource {
    /**
     * Domain to configure split DNS for. Requests for this domain will be resolved using the provided nameservers.
     * 
     */
    @Export(name="domain", refs={String.class}, tree="[0]")
    private Output<String> domain;

    /**
     * @return Domain to configure split DNS for. Requests for this domain will be resolved using the provided nameservers.
     * 
     */
    public Output<String> domain() {
        return this.domain;
    }
    /**
     * Devices on your network will use these nameservers to resolve DNS names. IPv4 or IPv6 addresses are accepted.
     * 
     */
    @Export(name="nameservers", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> nameservers;

    /**
     * @return Devices on your network will use these nameservers to resolve DNS names. IPv4 or IPv6 addresses are accepted.
     * 
     */
    public Output<List<String>> nameservers() {
        return this.nameservers;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public DnsSplitNameservers(String name) {
        this(name, DnsSplitNameserversArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public DnsSplitNameservers(String name, DnsSplitNameserversArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public DnsSplitNameservers(String name, DnsSplitNameserversArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("tailscale:index/dnsSplitNameservers:DnsSplitNameservers", name, args == null ? DnsSplitNameserversArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private DnsSplitNameservers(String name, Output<String> id, @Nullable DnsSplitNameserversState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("tailscale:index/dnsSplitNameservers:DnsSplitNameservers", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static DnsSplitNameservers get(String name, Output<String> id, @Nullable DnsSplitNameserversState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new DnsSplitNameservers(name, id, state, options);
    }
}
