// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.tailscale;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ProviderArgs extends com.pulumi.resources.ResourceArgs {

    public static final ProviderArgs Empty = new ProviderArgs();

    /**
     * The API key to use for authenticating requests to the API. Can be set via the TAILSCALE_API_KEY environment variable. If the value starts with &#39;file:&#39; then it is treated as a path to a file on disk that contains the API key. Conflicts with &#39;oauth_client_id&#39; and &#39;oauth_client_secret&#39;.
     * 
     */
    @Import(name="apiKey")
    private @Nullable Output<String> apiKey;

    /**
     * @return The API key to use for authenticating requests to the API. Can be set via the TAILSCALE_API_KEY environment variable. If the value starts with &#39;file:&#39; then it is treated as a path to a file on disk that contains the API key. Conflicts with &#39;oauth_client_id&#39; and &#39;oauth_client_secret&#39;.
     * 
     */
    public Optional<Output<String>> apiKey() {
        return Optional.ofNullable(this.apiKey);
    }

    /**
     * The OIDC audience to request when discovering an identity token from the runtime (GitHub Actions, AWS, or GCP) for workload identity federation. Can be set via the TAILSCALE_AUDIENCE environment variable. If the value starts with &#39;file:&#39; then it is treated as a path to a file on disk that contains the audience. Requires &#39;oauth_client_id&#39;. Conflicts with &#39;api_key&#39;, &#39;oauth_client_secret&#39;, &#39;identity_token&#39;, and &#39;identity_token_environment_variable_name&#39;.
     * 
     */
    @Import(name="audience")
    private @Nullable Output<String> audience;

    /**
     * @return The OIDC audience to request when discovering an identity token from the runtime (GitHub Actions, AWS, or GCP) for workload identity federation. Can be set via the TAILSCALE_AUDIENCE environment variable. If the value starts with &#39;file:&#39; then it is treated as a path to a file on disk that contains the audience. Requires &#39;oauth_client_id&#39;. Conflicts with &#39;api_key&#39;, &#39;oauth_client_secret&#39;, &#39;identity_token&#39;, and &#39;identity_token_environment_variable_name&#39;.
     * 
     */
    public Optional<Output<String>> audience() {
        return Optional.ofNullable(this.audience);
    }

    /**
     * The base URL of the Tailscale API. Defaults to https://api.tailscale.com. Can be set via the TAILSCALE_BASE_URL environment variable.
     * 
     */
    @Import(name="baseUrl")
    private @Nullable Output<String> baseUrl;

    /**
     * @return The base URL of the Tailscale API. Defaults to https://api.tailscale.com. Can be set via the TAILSCALE_BASE_URL environment variable.
     * 
     */
    public Optional<Output<String>> baseUrl() {
        return Optional.ofNullable(this.baseUrl);
    }

    /**
     * The jwt identity token to exchange for a Tailscale API token when using a federated identity. Can be set via the TAILSCALE_IDENTITY_TOKEN environment variable. If the value starts with &#39;file:&#39; then it is treated as a path to a file on disk that contains the identity token. Conflicts with &#39;api_key&#39;, &#39;oauth_client_secret&#39;, and &#39;identity_token_environment_variable_name&#39;.
     * 
     */
    @Import(name="identityToken")
    private @Nullable Output<String> identityToken;

    /**
     * @return The jwt identity token to exchange for a Tailscale API token when using a federated identity. Can be set via the TAILSCALE_IDENTITY_TOKEN environment variable. If the value starts with &#39;file:&#39; then it is treated as a path to a file on disk that contains the identity token. Conflicts with &#39;api_key&#39;, &#39;oauth_client_secret&#39;, and &#39;identity_token_environment_variable_name&#39;.
     * 
     */
    public Optional<Output<String>> identityToken() {
        return Optional.ofNullable(this.identityToken);
    }

    /**
     * The name of an environment variable to read the identity token from. This is useful when the identity token is provided by an external system (such as Terraform Cloud workload identity) in an environment variable you do not control. If the resolved value of the environment variable starts with &#39;file:&#39; then it is treated as a path to a file on disk that contains identity token. Conflicts with &#39;identity_token&#39;.
     * 
     */
    @Import(name="identityTokenEnvironmentVariableName")
    private @Nullable Output<String> identityTokenEnvironmentVariableName;

    /**
     * @return The name of an environment variable to read the identity token from. This is useful when the identity token is provided by an external system (such as Terraform Cloud workload identity) in an environment variable you do not control. If the resolved value of the environment variable starts with &#39;file:&#39; then it is treated as a path to a file on disk that contains identity token. Conflicts with &#39;identity_token&#39;.
     * 
     */
    public Optional<Output<String>> identityTokenEnvironmentVariableName() {
        return Optional.ofNullable(this.identityTokenEnvironmentVariableName);
    }

    /**
     * The OAuth application or federated identity&#39;s ID when using OAuth client credentials or workload identity federation. Can be set via the TAILSCALE_OAUTH_CLIENT_ID environment variable. If the value starts with &#39;file:&#39; then it is treated as a path to a file on disk that contains the client ID. Either &#39;oauth_client_secret&#39; or &#39;identity_token&#39; must be set alongside &#39;oauth_client_id&#39;. Conflicts with &#39;api_key&#39;.
     * 
     */
    @Import(name="oauthClientId")
    private @Nullable Output<String> oauthClientId;

    /**
     * @return The OAuth application or federated identity&#39;s ID when using OAuth client credentials or workload identity federation. Can be set via the TAILSCALE_OAUTH_CLIENT_ID environment variable. If the value starts with &#39;file:&#39; then it is treated as a path to a file on disk that contains the client ID. Either &#39;oauth_client_secret&#39; or &#39;identity_token&#39; must be set alongside &#39;oauth_client_id&#39;. Conflicts with &#39;api_key&#39;.
     * 
     */
    public Optional<Output<String>> oauthClientId() {
        return Optional.ofNullable(this.oauthClientId);
    }

    /**
     * The OAuth application&#39;s secret when using OAuth client credentials. Can be set via the TAILSCALE_OAUTH_CLIENT_SECRET environment variable. If the value starts with &#39;file:&#39; then it is treated as a path to a file on disk that contains the client secret. Conflicts with &#39;api_key&#39; and &#39;identity_token&#39;.
     * 
     */
    @Import(name="oauthClientSecret")
    private @Nullable Output<String> oauthClientSecret;

    /**
     * @return The OAuth application&#39;s secret when using OAuth client credentials. Can be set via the TAILSCALE_OAUTH_CLIENT_SECRET environment variable. If the value starts with &#39;file:&#39; then it is treated as a path to a file on disk that contains the client secret. Conflicts with &#39;api_key&#39; and &#39;identity_token&#39;.
     * 
     */
    public Optional<Output<String>> oauthClientSecret() {
        return Optional.ofNullable(this.oauthClientSecret);
    }

    /**
     * The OAuth 2.0 scopes to request when generating the access token using the supplied OAuth client credentials. See https://tailscale.com/kb/1623/trust-credentials#scopes for available scopes. Only valid when both &#39;oauth_client_id&#39; and &#39;oauth_client_secret&#39;, or both are set.
     * 
     */
    @Import(name="scopes", json=true)
    private @Nullable Output<List<String>> scopes;

    /**
     * @return The OAuth 2.0 scopes to request when generating the access token using the supplied OAuth client credentials. See https://tailscale.com/kb/1623/trust-credentials#scopes for available scopes. Only valid when both &#39;oauth_client_id&#39; and &#39;oauth_client_secret&#39;, or both are set.
     * 
     */
    public Optional<Output<List<String>>> scopes() {
        return Optional.ofNullable(this.scopes);
    }

    /**
     * The tailnet ID. Tailnets created before Oct 2025 can still use the legacy ID, but the Tailnet ID is the preferred identifier. Can be set via the TAILSCALE_TAILNET environment variable. Default is the tailnet that owns API credentials passed to the provider.
     * 
     */
    @Import(name="tailnet")
    private @Nullable Output<String> tailnet;

    /**
     * @return The tailnet ID. Tailnets created before Oct 2025 can still use the legacy ID, but the Tailnet ID is the preferred identifier. Can be set via the TAILSCALE_TAILNET environment variable. Default is the tailnet that owns API credentials passed to the provider.
     * 
     */
    public Optional<Output<String>> tailnet() {
        return Optional.ofNullable(this.tailnet);
    }

    /**
     * User-Agent header for API requests.
     * 
     */
    @Import(name="userAgent")
    private @Nullable Output<String> userAgent;

    /**
     * @return User-Agent header for API requests.
     * 
     */
    public Optional<Output<String>> userAgent() {
        return Optional.ofNullable(this.userAgent);
    }

    private ProviderArgs() {}

    private ProviderArgs(ProviderArgs $) {
        this.apiKey = $.apiKey;
        this.audience = $.audience;
        this.baseUrl = $.baseUrl;
        this.identityToken = $.identityToken;
        this.identityTokenEnvironmentVariableName = $.identityTokenEnvironmentVariableName;
        this.oauthClientId = $.oauthClientId;
        this.oauthClientSecret = $.oauthClientSecret;
        this.scopes = $.scopes;
        this.tailnet = $.tailnet;
        this.userAgent = $.userAgent;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ProviderArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ProviderArgs $;

        public Builder() {
            $ = new ProviderArgs();
        }

        public Builder(ProviderArgs defaults) {
            $ = new ProviderArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param apiKey The API key to use for authenticating requests to the API. Can be set via the TAILSCALE_API_KEY environment variable. If the value starts with &#39;file:&#39; then it is treated as a path to a file on disk that contains the API key. Conflicts with &#39;oauth_client_id&#39; and &#39;oauth_client_secret&#39;.
         * 
         * @return builder
         * 
         */
        public Builder apiKey(@Nullable Output<String> apiKey) {
            $.apiKey = apiKey;
            return this;
        }

        /**
         * @param apiKey The API key to use for authenticating requests to the API. Can be set via the TAILSCALE_API_KEY environment variable. If the value starts with &#39;file:&#39; then it is treated as a path to a file on disk that contains the API key. Conflicts with &#39;oauth_client_id&#39; and &#39;oauth_client_secret&#39;.
         * 
         * @return builder
         * 
         */
        public Builder apiKey(String apiKey) {
            return apiKey(Output.of(apiKey));
        }

        /**
         * @param audience The OIDC audience to request when discovering an identity token from the runtime (GitHub Actions, AWS, or GCP) for workload identity federation. Can be set via the TAILSCALE_AUDIENCE environment variable. If the value starts with &#39;file:&#39; then it is treated as a path to a file on disk that contains the audience. Requires &#39;oauth_client_id&#39;. Conflicts with &#39;api_key&#39;, &#39;oauth_client_secret&#39;, &#39;identity_token&#39;, and &#39;identity_token_environment_variable_name&#39;.
         * 
         * @return builder
         * 
         */
        public Builder audience(@Nullable Output<String> audience) {
            $.audience = audience;
            return this;
        }

        /**
         * @param audience The OIDC audience to request when discovering an identity token from the runtime (GitHub Actions, AWS, or GCP) for workload identity federation. Can be set via the TAILSCALE_AUDIENCE environment variable. If the value starts with &#39;file:&#39; then it is treated as a path to a file on disk that contains the audience. Requires &#39;oauth_client_id&#39;. Conflicts with &#39;api_key&#39;, &#39;oauth_client_secret&#39;, &#39;identity_token&#39;, and &#39;identity_token_environment_variable_name&#39;.
         * 
         * @return builder
         * 
         */
        public Builder audience(String audience) {
            return audience(Output.of(audience));
        }

        /**
         * @param baseUrl The base URL of the Tailscale API. Defaults to https://api.tailscale.com. Can be set via the TAILSCALE_BASE_URL environment variable.
         * 
         * @return builder
         * 
         */
        public Builder baseUrl(@Nullable Output<String> baseUrl) {
            $.baseUrl = baseUrl;
            return this;
        }

        /**
         * @param baseUrl The base URL of the Tailscale API. Defaults to https://api.tailscale.com. Can be set via the TAILSCALE_BASE_URL environment variable.
         * 
         * @return builder
         * 
         */
        public Builder baseUrl(String baseUrl) {
            return baseUrl(Output.of(baseUrl));
        }

        /**
         * @param identityToken The jwt identity token to exchange for a Tailscale API token when using a federated identity. Can be set via the TAILSCALE_IDENTITY_TOKEN environment variable. If the value starts with &#39;file:&#39; then it is treated as a path to a file on disk that contains the identity token. Conflicts with &#39;api_key&#39;, &#39;oauth_client_secret&#39;, and &#39;identity_token_environment_variable_name&#39;.
         * 
         * @return builder
         * 
         */
        public Builder identityToken(@Nullable Output<String> identityToken) {
            $.identityToken = identityToken;
            return this;
        }

        /**
         * @param identityToken The jwt identity token to exchange for a Tailscale API token when using a federated identity. Can be set via the TAILSCALE_IDENTITY_TOKEN environment variable. If the value starts with &#39;file:&#39; then it is treated as a path to a file on disk that contains the identity token. Conflicts with &#39;api_key&#39;, &#39;oauth_client_secret&#39;, and &#39;identity_token_environment_variable_name&#39;.
         * 
         * @return builder
         * 
         */
        public Builder identityToken(String identityToken) {
            return identityToken(Output.of(identityToken));
        }

        /**
         * @param identityTokenEnvironmentVariableName The name of an environment variable to read the identity token from. This is useful when the identity token is provided by an external system (such as Terraform Cloud workload identity) in an environment variable you do not control. If the resolved value of the environment variable starts with &#39;file:&#39; then it is treated as a path to a file on disk that contains identity token. Conflicts with &#39;identity_token&#39;.
         * 
         * @return builder
         * 
         */
        public Builder identityTokenEnvironmentVariableName(@Nullable Output<String> identityTokenEnvironmentVariableName) {
            $.identityTokenEnvironmentVariableName = identityTokenEnvironmentVariableName;
            return this;
        }

        /**
         * @param identityTokenEnvironmentVariableName The name of an environment variable to read the identity token from. This is useful when the identity token is provided by an external system (such as Terraform Cloud workload identity) in an environment variable you do not control. If the resolved value of the environment variable starts with &#39;file:&#39; then it is treated as a path to a file on disk that contains identity token. Conflicts with &#39;identity_token&#39;.
         * 
         * @return builder
         * 
         */
        public Builder identityTokenEnvironmentVariableName(String identityTokenEnvironmentVariableName) {
            return identityTokenEnvironmentVariableName(Output.of(identityTokenEnvironmentVariableName));
        }

        /**
         * @param oauthClientId The OAuth application or federated identity&#39;s ID when using OAuth client credentials or workload identity federation. Can be set via the TAILSCALE_OAUTH_CLIENT_ID environment variable. If the value starts with &#39;file:&#39; then it is treated as a path to a file on disk that contains the client ID. Either &#39;oauth_client_secret&#39; or &#39;identity_token&#39; must be set alongside &#39;oauth_client_id&#39;. Conflicts with &#39;api_key&#39;.
         * 
         * @return builder
         * 
         */
        public Builder oauthClientId(@Nullable Output<String> oauthClientId) {
            $.oauthClientId = oauthClientId;
            return this;
        }

        /**
         * @param oauthClientId The OAuth application or federated identity&#39;s ID when using OAuth client credentials or workload identity federation. Can be set via the TAILSCALE_OAUTH_CLIENT_ID environment variable. If the value starts with &#39;file:&#39; then it is treated as a path to a file on disk that contains the client ID. Either &#39;oauth_client_secret&#39; or &#39;identity_token&#39; must be set alongside &#39;oauth_client_id&#39;. Conflicts with &#39;api_key&#39;.
         * 
         * @return builder
         * 
         */
        public Builder oauthClientId(String oauthClientId) {
            return oauthClientId(Output.of(oauthClientId));
        }

        /**
         * @param oauthClientSecret The OAuth application&#39;s secret when using OAuth client credentials. Can be set via the TAILSCALE_OAUTH_CLIENT_SECRET environment variable. If the value starts with &#39;file:&#39; then it is treated as a path to a file on disk that contains the client secret. Conflicts with &#39;api_key&#39; and &#39;identity_token&#39;.
         * 
         * @return builder
         * 
         */
        public Builder oauthClientSecret(@Nullable Output<String> oauthClientSecret) {
            $.oauthClientSecret = oauthClientSecret;
            return this;
        }

        /**
         * @param oauthClientSecret The OAuth application&#39;s secret when using OAuth client credentials. Can be set via the TAILSCALE_OAUTH_CLIENT_SECRET environment variable. If the value starts with &#39;file:&#39; then it is treated as a path to a file on disk that contains the client secret. Conflicts with &#39;api_key&#39; and &#39;identity_token&#39;.
         * 
         * @return builder
         * 
         */
        public Builder oauthClientSecret(String oauthClientSecret) {
            return oauthClientSecret(Output.of(oauthClientSecret));
        }

        /**
         * @param scopes The OAuth 2.0 scopes to request when generating the access token using the supplied OAuth client credentials. See https://tailscale.com/kb/1623/trust-credentials#scopes for available scopes. Only valid when both &#39;oauth_client_id&#39; and &#39;oauth_client_secret&#39;, or both are set.
         * 
         * @return builder
         * 
         */
        public Builder scopes(@Nullable Output<List<String>> scopes) {
            $.scopes = scopes;
            return this;
        }

        /**
         * @param scopes The OAuth 2.0 scopes to request when generating the access token using the supplied OAuth client credentials. See https://tailscale.com/kb/1623/trust-credentials#scopes for available scopes. Only valid when both &#39;oauth_client_id&#39; and &#39;oauth_client_secret&#39;, or both are set.
         * 
         * @return builder
         * 
         */
        public Builder scopes(List<String> scopes) {
            return scopes(Output.of(scopes));
        }

        /**
         * @param scopes The OAuth 2.0 scopes to request when generating the access token using the supplied OAuth client credentials. See https://tailscale.com/kb/1623/trust-credentials#scopes for available scopes. Only valid when both &#39;oauth_client_id&#39; and &#39;oauth_client_secret&#39;, or both are set.
         * 
         * @return builder
         * 
         */
        public Builder scopes(String... scopes) {
            return scopes(List.of(scopes));
        }

        /**
         * @param tailnet The tailnet ID. Tailnets created before Oct 2025 can still use the legacy ID, but the Tailnet ID is the preferred identifier. Can be set via the TAILSCALE_TAILNET environment variable. Default is the tailnet that owns API credentials passed to the provider.
         * 
         * @return builder
         * 
         */
        public Builder tailnet(@Nullable Output<String> tailnet) {
            $.tailnet = tailnet;
            return this;
        }

        /**
         * @param tailnet The tailnet ID. Tailnets created before Oct 2025 can still use the legacy ID, but the Tailnet ID is the preferred identifier. Can be set via the TAILSCALE_TAILNET environment variable. Default is the tailnet that owns API credentials passed to the provider.
         * 
         * @return builder
         * 
         */
        public Builder tailnet(String tailnet) {
            return tailnet(Output.of(tailnet));
        }

        /**
         * @param userAgent User-Agent header for API requests.
         * 
         * @return builder
         * 
         */
        public Builder userAgent(@Nullable Output<String> userAgent) {
            $.userAgent = userAgent;
            return this;
        }

        /**
         * @param userAgent User-Agent header for API requests.
         * 
         * @return builder
         * 
         */
        public Builder userAgent(String userAgent) {
            return userAgent(Output.of(userAgent));
        }

        public ProviderArgs build() {
            $.userAgent = Codegen.stringProp("userAgent").output().arg($.userAgent).def("Pulumi/3.0 (https://www.pulumi.com) pulumi-tailscale/1.0.0-alpha.0+dev").getNullable();
            return $;
        }
    }

}
