// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.tailscale;

import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.tailscale.Utilities;
import com.pulumi.tailscale.inputs.Get4Via6Args;
import com.pulumi.tailscale.inputs.Get4Via6PlainArgs;
import com.pulumi.tailscale.inputs.GetDeviceArgs;
import com.pulumi.tailscale.inputs.GetDevicePlainArgs;
import com.pulumi.tailscale.inputs.GetDevicesArgs;
import com.pulumi.tailscale.inputs.GetDevicesPlainArgs;
import com.pulumi.tailscale.outputs.Get4Via6Result;
import com.pulumi.tailscale.outputs.GetDeviceResult;
import com.pulumi.tailscale.outputs.GetDevicesResult;
import java.util.concurrent.CompletableFuture;

public final class TailscaleFunctions {
    public static Output<Get4Via6Result> get4Via6(Get4Via6Args args) {
        return get4Via6(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<Get4Via6Result> get4Via6Plain(Get4Via6PlainArgs args) {
        return get4Via6Plain(args, InvokeOptions.Empty);
    }
    public static Output<Get4Via6Result> get4Via6(Get4Via6Args args, InvokeOptions options) {
        return Deployment.getInstance().invoke("tailscale:index/get4Via6:get4Via6", TypeShape.of(Get4Via6Result.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<Get4Via6Result> get4Via6Plain(Get4Via6PlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("tailscale:index/get4Via6:get4Via6", TypeShape.of(Get4Via6Result.class), args, Utilities.withVersion(options));
    }
    public static Output<GetDeviceResult> getDevice(GetDeviceArgs args) {
        return getDevice(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetDeviceResult> getDevicePlain(GetDevicePlainArgs args) {
        return getDevicePlain(args, InvokeOptions.Empty);
    }
    public static Output<GetDeviceResult> getDevice(GetDeviceArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("tailscale:index/getDevice:getDevice", TypeShape.of(GetDeviceResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<GetDeviceResult> getDevicePlain(GetDevicePlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("tailscale:index/getDevice:getDevice", TypeShape.of(GetDeviceResult.class), args, Utilities.withVersion(options));
    }
    public static Output<GetDevicesResult> getDevices() {
        return getDevices(GetDevicesArgs.Empty, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetDevicesResult> getDevicesPlain() {
        return getDevicesPlain(GetDevicesPlainArgs.Empty, InvokeOptions.Empty);
    }
    public static Output<GetDevicesResult> getDevices(GetDevicesArgs args) {
        return getDevices(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetDevicesResult> getDevicesPlain(GetDevicesPlainArgs args) {
        return getDevicesPlain(args, InvokeOptions.Empty);
    }
    public static Output<GetDevicesResult> getDevices(GetDevicesArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("tailscale:index/getDevices:getDevices", TypeShape.of(GetDevicesResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<GetDevicesResult> getDevicesPlain(GetDevicesPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("tailscale:index/getDevices:getDevices", TypeShape.of(GetDevicesResult.class), args, Utilities.withVersion(options));
    }
}
