// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.tailscale.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class Get4Via6Result {
    private String cidr;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    private String ipv6;
    private Integer site;

    private Get4Via6Result() {}
    public String cidr() {
        return this.cidr;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    public String ipv6() {
        return this.ipv6;
    }
    public Integer site() {
        return this.site;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(Get4Via6Result defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String cidr;
        private String id;
        private String ipv6;
        private Integer site;
        public Builder() {}
        public Builder(Get4Via6Result defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.cidr = defaults.cidr;
    	      this.id = defaults.id;
    	      this.ipv6 = defaults.ipv6;
    	      this.site = defaults.site;
        }

        @CustomType.Setter
        public Builder cidr(String cidr) {
            this.cidr = Objects.requireNonNull(cidr);
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder ipv6(String ipv6) {
            this.ipv6 = Objects.requireNonNull(ipv6);
            return this;
        }
        @CustomType.Setter
        public Builder site(Integer site) {
            this.site = Objects.requireNonNull(site);
            return this;
        }
        public Get4Via6Result build() {
            final var o = new Get4Via6Result();
            o.cidr = cidr;
            o.id = id;
            o.ipv6 = ipv6;
            o.site = site;
            return o;
        }
    }
}
