// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.tailscale.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetDeviceResult {
    /**
     * @return The list of device&#39;s IPs
     * 
     */
    private List<String> addresses;
    /**
     * @return The short hostname of the device
     * 
     */
    private @Nullable String hostname;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return The full name of the device (e.g. `hostname.domain.ts.net`)
     * 
     */
    private @Nullable String name;
    /**
     * @return The preferred indentifier for a device.
     * 
     */
    private String nodeId;
    /**
     * @return The tags applied to the device
     * 
     */
    private List<String> tags;
    /**
     * @return The user associated with the device
     * 
     */
    private String user;
    /**
     * @return If specified, the provider will make multiple attempts to obtain the data source until the wait_for duration is reached. Retries are made every second so this value should be greater than 1s
     * 
     */
    private @Nullable String waitFor;

    private GetDeviceResult() {}
    /**
     * @return The list of device&#39;s IPs
     * 
     */
    public List<String> addresses() {
        return this.addresses;
    }
    /**
     * @return The short hostname of the device
     * 
     */
    public Optional<String> hostname() {
        return Optional.ofNullable(this.hostname);
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return The full name of the device (e.g. `hostname.domain.ts.net`)
     * 
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }
    /**
     * @return The preferred indentifier for a device.
     * 
     */
    public String nodeId() {
        return this.nodeId;
    }
    /**
     * @return The tags applied to the device
     * 
     */
    public List<String> tags() {
        return this.tags;
    }
    /**
     * @return The user associated with the device
     * 
     */
    public String user() {
        return this.user;
    }
    /**
     * @return If specified, the provider will make multiple attempts to obtain the data source until the wait_for duration is reached. Retries are made every second so this value should be greater than 1s
     * 
     */
    public Optional<String> waitFor() {
        return Optional.ofNullable(this.waitFor);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetDeviceResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<String> addresses;
        private @Nullable String hostname;
        private String id;
        private @Nullable String name;
        private String nodeId;
        private List<String> tags;
        private String user;
        private @Nullable String waitFor;
        public Builder() {}
        public Builder(GetDeviceResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.addresses = defaults.addresses;
    	      this.hostname = defaults.hostname;
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.nodeId = defaults.nodeId;
    	      this.tags = defaults.tags;
    	      this.user = defaults.user;
    	      this.waitFor = defaults.waitFor;
        }

        @CustomType.Setter
        public Builder addresses(List<String> addresses) {
            if (addresses == null) {
              throw new MissingRequiredPropertyException("GetDeviceResult", "addresses");
            }
            this.addresses = addresses;
            return this;
        }
        public Builder addresses(String... addresses) {
            return addresses(List.of(addresses));
        }
        @CustomType.Setter
        public Builder hostname(@Nullable String hostname) {

            this.hostname = hostname;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetDeviceResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder name(@Nullable String name) {

            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder nodeId(String nodeId) {
            if (nodeId == null) {
              throw new MissingRequiredPropertyException("GetDeviceResult", "nodeId");
            }
            this.nodeId = nodeId;
            return this;
        }
        @CustomType.Setter
        public Builder tags(List<String> tags) {
            if (tags == null) {
              throw new MissingRequiredPropertyException("GetDeviceResult", "tags");
            }
            this.tags = tags;
            return this;
        }
        public Builder tags(String... tags) {
            return tags(List.of(tags));
        }
        @CustomType.Setter
        public Builder user(String user) {
            if (user == null) {
              throw new MissingRequiredPropertyException("GetDeviceResult", "user");
            }
            this.user = user;
            return this;
        }
        @CustomType.Setter
        public Builder waitFor(@Nullable String waitFor) {

            this.waitFor = waitFor;
            return this;
        }
        public GetDeviceResult build() {
            final var _resultValue = new GetDeviceResult();
            _resultValue.addresses = addresses;
            _resultValue.hostname = hostname;
            _resultValue.id = id;
            _resultValue.name = name;
            _resultValue.nodeId = nodeId;
            _resultValue.tags = tags;
            _resultValue.user = user;
            _resultValue.waitFor = waitFor;
            return _resultValue;
        }
    }
}
