// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tailscale.Inputs
{

    public sealed class DnsConfigurationSplitDnArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The nameservers will be used only for this domain.
        /// </summary>
        [Input("domain", required: true)]
        public Input<string> Domain { get; set; } = null!;

        [Input("nameservers", required: true)]
        private InputList<Inputs.DnsConfigurationSplitDnNameserverArgs>? _nameservers;

        /// <summary>
        /// Set the nameservers used by devices on your network to resolve DNS queries.
        /// </summary>
        public InputList<Inputs.DnsConfigurationSplitDnNameserverArgs> Nameservers
        {
            get => _nameservers ?? (_nameservers = new InputList<Inputs.DnsConfigurationSplitDnNameserverArgs>());
            set => _nameservers = value;
        }

        public DnsConfigurationSplitDnArgs()
        {
        }
        public static new DnsConfigurationSplitDnArgs Empty => new DnsConfigurationSplitDnArgs();
    }
}
