// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * The contacts resource allows you to configure contact details for your Tailscale network. See https://tailscale.com/kb/1224/contact-preferences for more information.
 *
 * Destroying this resource does not unset or modify values in the tailscale control plane, and simply removes the resource from Terraform state.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as tailscale from "@pulumi/tailscale";
 *
 * const sampleContacts = new tailscale.Contacts("sample_contacts", {
 *     accounts: [{
 *         email: "account@example.com",
 *     }],
 *     supports: [{
 *         email: "support@example.com",
 *     }],
 *     securities: [{
 *         email: "security@example.com",
 *     }],
 * });
 * ```
 *
 * ## Import
 *
 * The `pulumi import` command can be used, for example:
 *
 * ID doesn't matter.
 *
 * ```sh
 * $ pulumi import tailscale:index/contacts:Contacts sample_contacts contacts
 * ```
 */
export class Contacts extends pulumi.CustomResource {
    /**
     * Get an existing Contacts resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ContactsState, opts?: pulumi.CustomResourceOptions): Contacts {
        return new Contacts(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'tailscale:index/contacts:Contacts';

    /**
     * Returns true if the given object is an instance of Contacts.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Contacts {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Contacts.__pulumiType;
    }

    /**
     * Configuration for communications about important changes to your tailnet
     */
    declare public readonly accounts: pulumi.Output<outputs.ContactsAccount[] | undefined>;
    /**
     * Configuration for communications about security issues affecting your tailnet
     */
    declare public readonly securities: pulumi.Output<outputs.ContactsSecurity[] | undefined>;
    /**
     * Configuration for communications about misconfigurations in your tailnet
     */
    declare public readonly supports: pulumi.Output<outputs.ContactsSupport[] | undefined>;

    /**
     * Create a Contacts resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ContactsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ContactsArgs | ContactsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ContactsState | undefined;
            resourceInputs["accounts"] = state?.accounts;
            resourceInputs["securities"] = state?.securities;
            resourceInputs["supports"] = state?.supports;
        } else {
            const args = argsOrState as ContactsArgs | undefined;
            resourceInputs["accounts"] = args?.accounts;
            resourceInputs["securities"] = args?.securities;
            resourceInputs["supports"] = args?.supports;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Contacts.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Contacts resources.
 */
export interface ContactsState {
    /**
     * Configuration for communications about important changes to your tailnet
     */
    accounts?: pulumi.Input<pulumi.Input<inputs.ContactsAccount>[] | undefined>;
    /**
     * Configuration for communications about security issues affecting your tailnet
     */
    securities?: pulumi.Input<pulumi.Input<inputs.ContactsSecurity>[] | undefined>;
    /**
     * Configuration for communications about misconfigurations in your tailnet
     */
    supports?: pulumi.Input<pulumi.Input<inputs.ContactsSupport>[] | undefined>;
}

/**
 * The set of arguments for constructing a Contacts resource.
 */
export interface ContactsArgs {
    /**
     * Configuration for communications about important changes to your tailnet
     */
    accounts?: pulumi.Input<pulumi.Input<inputs.ContactsAccount>[] | undefined>;
    /**
     * Configuration for communications about security issues affecting your tailnet
     */
    securities?: pulumi.Input<pulumi.Input<inputs.ContactsSecurity>[] | undefined>;
    /**
     * Configuration for communications about misconfigurations in your tailnet
     */
    supports?: pulumi.Input<pulumi.Input<inputs.ContactsSupport>[] | undefined>;
}
