// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The acl data source gets the Tailscale ACL for a tailnet
 */
export function getAcl(opts?: pulumi.InvokeOptions): Promise<GetAclResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("tailscale:index/getAcl:getAcl", {
    }, opts);
}

/**
 * A collection of values returned by getAcl.
 */
export interface GetAclResult {
    /**
     * The contents of Tailscale ACL as a HuJSON string
     */
    readonly hujson: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The contents of Tailscale ACL as a JSON string
     */
    readonly json: string;
}
/**
 * The acl data source gets the Tailscale ACL for a tailnet
 */
export function getAclOutput(opts?: pulumi.InvokeOptions): pulumi.Output<GetAclResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("tailscale:index/getAcl:getAcl", {
    }, opts);
}
