// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The Service data source describes a single Service in a tailnet. See https://tailscale.com/docs/features/tailscale-services for more information.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as tailscale from "@pulumi/tailscale";
 *
 * const example = tailscale.getService({
 *     name: "svc:my-service",
 * });
 * ```
 */
export function getService(args: GetServiceArgs, opts?: pulumi.InvokeOptions): Promise<GetServiceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("tailscale:index/getService:getService", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getService.
 */
export interface GetServiceArgs {
    /**
     * The name of the Service (e.g. `svc:my-service`).
     */
    name: string;
}

/**
 * A collection of values returned by getService.
 */
export interface GetServiceResult {
    /**
     * The IP addresses assigned to the Service.
     */
    readonly addrs: string[];
    /**
     * A comment describing the Service.
     */
    readonly comment: string;
    /**
     * The Service name, e.g. 'svc:my-service'.
     */
    readonly id: string;
    /**
     * The name of the Service (e.g. `svc:my-service`).
     */
    readonly name: string;
    /**
     * The ports that the Service listens on.
     */
    readonly ports: string[];
    /**
     * The ACL tags applied to the Service.
     */
    readonly tags: string[];
}
/**
 * The Service data source describes a single Service in a tailnet. See https://tailscale.com/docs/features/tailscale-services for more information.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as tailscale from "@pulumi/tailscale";
 *
 * const example = tailscale.getService({
 *     name: "svc:my-service",
 * });
 * ```
 */
export function getServiceOutput(args: GetServiceOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetServiceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("tailscale:index/getService:getService", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getService.
 */
export interface GetServiceOutputArgs {
    /**
     * The name of the Service (e.g. `svc:my-service`).
     */
    name: pulumi.Input<string>;
}
